//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api_TableSaveData
    {
        public int Id { get; set; }
        public string NameSyncdata { get; set; }
        public string HrefApi { get; set; }
        public string TypeApi { get; set; }
        public string InputApi { get; set; }
        public string TableNameSaveData { get; set; }
        public bool IsActive { get; set; }
    }
}
