//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistTest
    {
        public int Id { get; set; }
        public string CodeTCV { get; set; }
        public string Customer_Code { get; set; }
        public int DayTest { get; set; }
        public int MonthTest { get; set; }
        public int YearTest { get; set; }
        public string Note { get; set; }
        public int CityId { get; set; }
        public int TestGroupId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> ThuocLa_Diem { get; set; }
        public string ThuocLa_NguyCo { get; set; }
        public Nullable<decimal> ConRuou_Diem { get; set; }
        public string ConRuou_NguyCo { get; set; }
        public Nullable<decimal> CanSa_Diem { get; set; }
        public string CanSa_NguyCo { get; set; }
        public Nullable<decimal> Cocaine_Diem { get; set; }
        public string Cocaine_NguyCo { get; set; }
        public Nullable<decimal> MaTuyDa_Diem { get; set; }
        public string MaTuyDa_NguyCo { get; set; }
        public Nullable<decimal> KhiXongHit_Diem { get; set; }
        public string KhiXongHit_NguyCo { get; set; }
        public Nullable<decimal> ThuocAnThan_Diem { get; set; }
        public string ThuocAnThan_NguyCo { get; set; }
        public Nullable<decimal> ChatGayAoGiac_Diem { get; set; }
        public string ChatGayAoGiac_NguyCo { get; set; }
        public Nullable<decimal> ChatThuocPhien_Diem { get; set; }
        public string ChatThuocPhien_NguyCo { get; set; }
        public Nullable<decimal> CacThuocKhac_Diem { get; set; }
        public string CacThuocKhac_NguyCo { get; set; }
    }
}
