//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaoCaoBVTLEntities : DbContext
    {
        public BaoCaoBVTLEntities()
            : base("name=BaoCaoBVTLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACETest> ACETests { get; set; }
        public virtual DbSet<Api_TableSaveData> Api_TableSaveData { get; set; }
        public virtual DbSet<AssistTest> AssistTests { get; set; }
        public virtual DbSet<BVTL_API> BVTL_API { get; set; }
        public virtual DbSet<BVTL_CHAT_GAY_NGHIEN_3TH> BVTL_CHAT_GAY_NGHIEN_3TH { get; set; }
        public virtual DbSet<BVTL_CHAT_GAY_NGHIEN_TX3TH> BVTL_CHAT_GAY_NGHIEN_TX3TH { get; set; }
        public virtual DbSet<BVTL_DUONG_SU_DUNG> BVTL_DUONG_SU_DUNG { get; set; }
        public virtual DbSet<BVTL_KHACH_HANG> BVTL_KHACH_HANG { get; set; }
        public virtual DbSet<BVTL_KQ_SL_ACE> BVTL_KQ_SL_ACE { get; set; }
        public virtual DbSet<BVTL_KQ_SL_ASSIST> BVTL_KQ_SL_ASSIST { get; set; }
        public virtual DbSet<BVTL_KQ_SL_SKTT> BVTL_KQ_SL_SKTT { get; set; }
        public virtual DbSet<BVTL_KQ_XN_HIV> BVTL_KQ_XN_HIV { get; set; }
        public virtual DbSet<BVTL_LOAI_DOI_TUONG> BVTL_LOAI_DOI_TUONG { get; set; }
        public virtual DbSet<BVTL_MASTER_TABLE> BVTL_MASTER_TABLE { get; set; }
        public virtual DbSet<BVTL_NHOM_TBH> BVTL_NHOM_TBH { get; set; }
        public virtual DbSet<BVTL_TAN_SUAT_SU_DUNG> BVTL_TAN_SUAT_SU_DUNG { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryService> DeliveryServices { get; set; }
        public virtual DbSet<HTVTest> HTVTests { get; set; }
        public virtual DbSet<PageAction> PageActions { get; set; }
        public virtual DbSet<PageMenu> PageMenus { get; set; }
        public virtual DbSet<ProvideReductionItem> ProvideReductionItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePage> RolePages { get; set; }
        public virtual DbSet<SKTTTest> SKTTTests { get; set; }
        public virtual DbSet<SocialSupport> SocialSupports { get; set; }
        public virtual DbSet<SysLog> SysLogs { get; set; }
        public virtual DbSet<SysParameter> SysParameters { get; set; }
        public virtual DbSet<TestGroup> TestGroups { get; set; }
        public virtual DbSet<UrineTest> UrineTests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_TestGroup> User_TestGroup { get; set; }
    }
}
