//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaoCaoBVTLEntities : DbContext
    {
        public BaoCaoBVTLEntities()
            : base("name=BaoCaoBVTLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACETest> ACETests { get; set; }
        public virtual DbSet<Api_TableSaveData> Api_TableSaveData { get; set; }
        public virtual DbSet<AssistTest> AssistTests { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryService> DeliveryServices { get; set; }
        public virtual DbSet<HTVTest> HTVTests { get; set; }
        public virtual DbSet<PageAction> PageActions { get; set; }
        public virtual DbSet<PageMenu> PageMenus { get; set; }
        public virtual DbSet<ProvideReductionItem> ProvideReductionItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePage> RolePages { get; set; }
        public virtual DbSet<SKTTTest> SKTTTests { get; set; }
        public virtual DbSet<SocialSupport> SocialSupports { get; set; }
        public virtual DbSet<SysLog> SysLogs { get; set; }
        public virtual DbSet<SysParameter> SysParameters { get; set; }
        public virtual DbSet<TestGroup> TestGroups { get; set; }
        public virtual DbSet<UrineTest> UrineTests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_TestGroup> User_TestGroup { get; set; }
    }
}
