//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_MASTER_TABLE
    {
        public int table_id { get; set; }
        public string table_name { get; set; }
        public int table_status { get; set; }
        public Nullable<int> Api_Id { get; set; }
    
        public virtual BVTL_API BVTL_API { get; set; }
    }
}
