//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_CITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BVTL_CITES()
        {
            this.BVTL_BO_BIEU_MAU_KH_BAO_CAO = new HashSet<BVTL_BO_BIEU_MAU_KH_BAO_CAO>();
            this.BVTL_KQ_XN_NUOC_TIEU = new HashSet<BVTL_KQ_XN_NUOC_TIEU>();
            this.BVTL_KQ_SL_ACE = new HashSet<BVTL_KQ_SL_ACE>();
            this.BVTL_KQ_SL_ASSIST = new HashSet<BVTL_KQ_SL_ASSIST>();
            this.BVTL_KQ_SL_SKTT = new HashSet<BVTL_KQ_SL_SKTT>();
            this.BVTL_KQ_XN_HIV = new HashSet<BVTL_KQ_XN_HIV>();
            this.BVTL_NHOM_TBH = new HashSet<BVTL_NHOM_TBH>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_BO_BIEU_MAU_KH_BAO_CAO> BVTL_BO_BIEU_MAU_KH_BAO_CAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_XN_NUOC_TIEU> BVTL_KQ_XN_NUOC_TIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ACE> BVTL_KQ_SL_ACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ASSIST> BVTL_KQ_SL_ASSIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_SKTT> BVTL_KQ_SL_SKTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_XN_HIV> BVTL_KQ_XN_HIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_NHOM_TBH> BVTL_NHOM_TBH { get; set; }
    }
}
