//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_KQ_XN_HIV
    {
        public int kqxnhiv_id { get; set; }
        public int khachhang_id { get; set; }
        public System.DateTime ngayxn { get; set; }
        public int ngayxn_date { get; set; }
        public int ngayxn_month { get; set; }
        public int ngayxn_year { get; set; }
        public int ketqua { get; set; }
        public Nullable<int> dangdieutri_hiv { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_KHACH_HANG BVTL_KHACH_HANG { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
