//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BVTL_REPORTINGEntities : DbContext
    {
        public BVTL_REPORTINGEntities()
            : base("name=BVTL_REPORTINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BVTL_API> BVTL_API { get; set; }
        public virtual DbSet<BVTL_BO_BIEU_MAU_KH_BAO_CAO> BVTL_BO_BIEU_MAU_KH_BAO_CAO { get; set; }
        public virtual DbSet<BVTL_CHAT_GAY_NGHIEN_3TH> BVTL_CHAT_GAY_NGHIEN_3TH { get; set; }
        public virtual DbSet<BVTL_CHAT_GAY_NGHIEN_TX3TH> BVTL_CHAT_GAY_NGHIEN_TX3TH { get; set; }
        public virtual DbSet<BVTL_CHUYEN_GUI_DICH_VU> BVTL_CHUYEN_GUI_DICH_VU { get; set; }
        public virtual DbSet<BVTL_CITES> BVTL_CITES { get; set; }
        public virtual DbSet<BVTL_DU_AN> BVTL_DU_AN { get; set; }
        public virtual DbSet<BVTL_DUONG_SU_DUNG> BVTL_DUONG_SU_DUNG { get; set; }
        public virtual DbSet<BVTL_KHACH_HANG> BVTL_KHACH_HANG { get; set; }
        public virtual DbSet<BVTL_KQ_SL_ACE> BVTL_KQ_SL_ACE { get; set; }
        public virtual DbSet<BVTL_KQ_SL_ASSIST> BVTL_KQ_SL_ASSIST { get; set; }
        public virtual DbSet<BVTL_KQ_SL_SKTT> BVTL_KQ_SL_SKTT { get; set; }
        public virtual DbSet<BVTL_KQ_XN_HIV> BVTL_KQ_XN_HIV { get; set; }
        public virtual DbSet<BVTL_LOAI_DOI_TUONG> BVTL_LOAI_DOI_TUONG { get; set; }
        public virtual DbSet<BVTL_MASTER_TABLE> BVTL_MASTER_TABLE { get; set; }
        public virtual DbSet<BVTL_NHOM_TBH> BVTL_NHOM_TBH { get; set; }
        public virtual DbSet<BVTL_PHIEU_TU_VAN> BVTL_PHIEU_TU_VAN { get; set; }
        public virtual DbSet<BVTL_QT_LOG> BVTL_QT_LOG { get; set; }
        public virtual DbSet<BVTL_QT_NGUOI_DUNG> BVTL_QT_NGUOI_DUNG { get; set; }
        public virtual DbSet<BVTL_QT_NGUOI_DUNG_NHOM_TBH> BVTL_QT_NGUOI_DUNG_NHOM_TBH { get; set; }
        public virtual DbSet<BVTL_QT_PAGE_ACTION> BVTL_QT_PAGE_ACTION { get; set; }
        public virtual DbSet<BVTL_QT_PAGE_MENU> BVTL_QT_PAGE_MENU { get; set; }
        public virtual DbSet<BVTL_QT_QUYEN> BVTL_QT_QUYEN { get; set; }
        public virtual DbSet<BVTL_QT_QUYEN_PAGE> BVTL_QT_QUYEN_PAGE { get; set; }
        public virtual DbSet<BVTL_QT_THAM_SO> BVTL_QT_THAM_SO { get; set; }
        public virtual DbSet<BVTL_TAN_SUAT_SU_DUNG> BVTL_TAN_SUAT_SU_DUNG { get; set; }
        public virtual DbSet<CHITIEU_DUAN> CHITIEU_DUAN { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
