//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_KQ_SL_ASSIST
    {
        public int kqslassist_id { get; set; }
        public int khachhang_id { get; set; }
        public System.DateTime ngaysl { get; set; }
        public int ngaysl_date { get; set; }
        public int ngaysl_month { get; set; }
        public int ngaysl_year { get; set; }
        public Nullable<int> thuocla_diem { get; set; }
        public string thuocla_nguyco { get; set; }
        public Nullable<int> conruou_diem { get; set; }
        public string conruou_nguyco { get; set; }
        public Nullable<int> cansa_diem { get; set; }
        public string cansa_nguyco { get; set; }
        public Nullable<int> cocaine_diem { get; set; }
        public string cocaine_nguyco { get; set; }
        public Nullable<int> matuyda_diem { get; set; }
        public string matuyda_nguyco { get; set; }
        public Nullable<int> khixonghit_diem { get; set; }
        public string khixonghit_nguyco { get; set; }
        public Nullable<int> thuocanthan_diem { get; set; }
        public string thuocanthan_nguyco { get; set; }
        public Nullable<int> chatgayaogiac_diem { get; set; }
        public string chatgayaogiac_nguyco { get; set; }
        public Nullable<int> thuocphien_diem { get; set; }
        public string thuocphien_nguyco { get; set; }
        public Nullable<int> chatkhac_diem { get; set; }
        public string chatkhac_nguyco { get; set; }
        public string ghichu { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_KHACH_HANG BVTL_KHACH_HANG { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
