//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_PHIEU_TU_VAN
    {
        public long record_id { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<System.DateTime> ngaytuvan { get; set; }
        public string diadiem { get; set; }
        public string matcv { get; set; }
        public string lantuvan { get; set; }
        public string cau1_1 { get; set; }
        public string cau1_1k { get; set; }
        public string cau1_2 { get; set; }
        public string cau1_3 { get; set; }
        public string cau1_4 { get; set; }
        public string cau1_5 { get; set; }
        public string cau2 { get; set; }
        public string cau2_1k { get; set; }
        public string cau2_2 { get; set; }
        public string cau3 { get; set; }
        public string cau3_1k { get; set; }
        public string cau3_1k_2 { get; set; }
        public string cau4 { get; set; }
        public string cau4_1k { get; set; }
        public string cau4_1k_2 { get; set; }
        public string cau5_1 { get; set; }
        public string cau5_1k { get; set; }
        public string cau5_1_2 { get; set; }
        public string cau5_2 { get; set; }
        public string cau5_2k { get; set; }
        public string cau5_2k_2 { get; set; }
        public string cau5_3 { get; set; }
        public string cau5_3_1 { get; set; }
        public string cau5_4 { get; set; }
        public string cau5_4_1 { get; set; }
        public string cau5_5 { get; set; }
        public string cau5_4_2 { get; set; }
        public string cau5_6 { get; set; }
        public string cau5_6k { get; set; }
        public string cau5_6k_2 { get; set; }
        public string cau5_7 { get; set; }
        public string cau5_7k { get; set; }
        public string cau5_7k_3 { get; set; }
        public string cau5_8 { get; set; }
        public string cau5_7k_2 { get; set; }
        public string tongket { get; set; }
        public string tuvantiep { get; set; }
        public string vande { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<int> khachhang_id { get; set; }
        public string sottkh { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public int ngaytuvan_date { get; set; }
        public int ngaytuvan_month { get; set; }
        public int ngaytuvan_year { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public string maduan { get; set; }
    
        public virtual BVTL_KHACH_HANG BVTL_KHACH_HANG { get; set; }
    }
}
