//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_THEO_DAU_KH
    {
        public int record_id { get; set; }
        public string makh { get; set; }
        public System.DateTime day { get; set; }
        public int ngayth_date { get; set; }
        public int ngayth_month { get; set; }
        public int ngayth_year { get; set; }
        public string hinhthuc { get; set; }
        public string hinhthuc_khac { get; set; }
        public string kq { get; set; }
        public string khac { get; set; }
        public string ghichu { get; set; }
        public string theo_du_kh_complete { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public Nullable<int> record_id_api { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_DU_AN BVTL_DU_AN { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
