//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_CITES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BVTL_CITES()
        {
            this.BVTL_BO_BIEU_MAU_KH_BAO_CAO = new HashSet<BVTL_BO_BIEU_MAU_KH_BAO_CAO>();
            this.BVTL_KQ_XN_NUOC_TIEU = new HashSet<BVTL_KQ_XN_NUOC_TIEU>();
            this.BVTL_KQ_SL_ACE = new HashSet<BVTL_KQ_SL_ACE>();
            this.BVTL_KQ_SL_ASSIST = new HashSet<BVTL_KQ_SL_ASSIST>();
            this.BVTL_KQ_SL_SKTT = new HashSet<BVTL_KQ_SL_SKTT>();
            this.BVTL_KQ_XN_HIV = new HashSet<BVTL_KQ_XN_HIV>();
            this.BVTL_NHOM_TBH = new HashSet<BVTL_NHOM_TBH>();
            this.VIIV_DANH_GIA_HAI_LONG = new HashSet<VIIV_DANH_GIA_HAI_LONG>();
            this.VIIV_TRAINING_DATA_COLLECTION = new HashSet<VIIV_TRAINING_DATA_COLLECTION>();
            this.VIIV_TT_KH_MAT_DAU = new HashSet<VIIV_TT_KH_MAT_DAU>();
            this.VIIV_THONG_TIN_TRUYEN_THONG = new HashSet<VIIV_THONG_TIN_TRUYEN_THONG>();
            this.BVTL_THONG_TIN_TRUYEN_THONG = new HashSet<BVTL_THONG_TIN_TRUYEN_THONG>();
            this.BVTL_THEO_DAU_KH = new HashSet<BVTL_THEO_DAU_KH>();
            this.CH07_THONG_TIN_TRUYEN_THONG = new HashSet<CH07_THONG_TIN_TRUYEN_THONG>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdateBy { get; set; }
        public string Code_Map { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_BO_BIEU_MAU_KH_BAO_CAO> BVTL_BO_BIEU_MAU_KH_BAO_CAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_XN_NUOC_TIEU> BVTL_KQ_XN_NUOC_TIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ACE> BVTL_KQ_SL_ACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ASSIST> BVTL_KQ_SL_ASSIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_SKTT> BVTL_KQ_SL_SKTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_XN_HIV> BVTL_KQ_XN_HIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_NHOM_TBH> BVTL_NHOM_TBH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIIV_DANH_GIA_HAI_LONG> VIIV_DANH_GIA_HAI_LONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIIV_TRAINING_DATA_COLLECTION> VIIV_TRAINING_DATA_COLLECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIIV_TT_KH_MAT_DAU> VIIV_TT_KH_MAT_DAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIIV_THONG_TIN_TRUYEN_THONG> VIIV_THONG_TIN_TRUYEN_THONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_THONG_TIN_TRUYEN_THONG> BVTL_THONG_TIN_TRUYEN_THONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_THEO_DAU_KH> BVTL_THEO_DAU_KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CH07_THONG_TIN_TRUYEN_THONG> CH07_THONG_TIN_TRUYEN_THONG { get; set; }
    }
}
