//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_KHACH_HANG
    {
        public int khachhang_id { get; set; }
        public string makh { get; set; }
        public string sottkh { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> namsinh { get; set; }
        public Nullable<int> loai_doi_tuong_id { get; set; }
        public Nullable<System.DateTime> ngaytiepcan { get; set; }
        public Nullable<System.DateTime> ngayngungchamsoc { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
