//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_CHUYEN_GUI_DICH_VU
    {
        public long record_id { get; set; }
        public string loaihinh { get; set; }
        public Nullable<System.DateTime> ngay_xn { get; set; }
        public string diachi_xn { get; set; }
        public string kq_xn { get; set; }
        public string dieutri { get; set; }
        public string diachi_cg { get; set; }
        public Nullable<System.DateTime> ngay_bddt { get; set; }
        public string taiuong_bd { get; set; }
        public string anh1 { get; set; }
        public string taiuong_bd_2 { get; set; }
        public string anh2 { get; set; }
        public string taiuong_bd_21 { get; set; }
        public string anh3 { get; set; }
        public string s3t { get; set; }
        public string s6t { get; set; }
        public string s9t { get; set; }
        public string s12t { get; set; }
        public Nullable<System.DateTime> ngaykham { get; set; }
        public string diachikham { get; set; }
        public string lankham { get; set; }
        public string chandoan { get; set; }
        public string khac { get; set; }
        public string kedon { get; set; }
        public string dungthuoc { get; set; }
        public string hotro { get; set; }
        public Nullable<System.DateTime> ngaykxn { get; set; }
        public string diachi_kxn { get; set; }
        public string lan_xnk { get; set; }
        public string chandoan1 { get; set; }
        public string khac_sti { get; set; }
        public string dieutri_sti { get; set; }
        public string hotro_sti { get; set; }
        public string hotro_bhyt { get; set; }
        public string makh { get; set; }
        public string sottkh { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public int ngay_xn_date { get; set; }
        public int ngay_xn_month { get; set; }
        public int ngay_xn_year { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public string maduan { get; set; }
        public string hotro_gttt { get; set; }
        public Nullable<System.DateTime> ngayhotro_2 { get; set; }
        public string hotro_pep { get; set; }
        public string hotro_c { get; set; }
        public string hotro_c_2 { get; set; }
        public string hotro_lao { get; set; }
        public string hotro_lao_2 { get; set; }
        public string hotro_mtd { get; set; }
        public string hotro_prep { get; set; }
        public Nullable<System.DateTime> ngay_ht { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
