//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_CHAT_GAY_NGHIEN_3TH
    {
        public int id { get; set; }
        public string ten_cgn { get; set; }
        public string ghichu { get; set; }
    }
}
