//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BVTL_KHACH_HANG()
        {
            this.BVTL_KQ_SL_ACE = new HashSet<BVTL_KQ_SL_ACE>();
            this.BVTL_KQ_SL_ASSIST = new HashSet<BVTL_KQ_SL_ASSIST>();
            this.BVTL_KQ_SL_SKTT = new HashSet<BVTL_KQ_SL_SKTT>();
            this.BVTL_KQ_XN_HIV = new HashSet<BVTL_KQ_XN_HIV>();
        }
    
        public int khachhang_id { get; set; }
        public string makh { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> namsinh { get; set; }
        public Nullable<int> loai_doi_tuong_id { get; set; }
        public Nullable<System.DateTime> ngaytiepcan { get; set; }
        public Nullable<System.DateTime> ngayngungchamsoc { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public Nullable<int> city_id { get; set; }
    
        public virtual BVTL_LOAI_DOI_TUONG BVTL_LOAI_DOI_TUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ACE> BVTL_KQ_SL_ACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_ASSIST> BVTL_KQ_SL_ASSIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_SL_SKTT> BVTL_KQ_SL_SKTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_KQ_XN_HIV> BVTL_KQ_XN_HIV { get; set; }
        public virtual City City { get; set; }
    }
}
