//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_KQ_SL_SKTT
    {
        public int kqslsktt_id { get; set; }
        public Nullable<int> khachhang_id { get; set; }
        public System.DateTime ngaysl { get; set; }
        public int ngaysl_date { get; set; }
        public int ngaysl_month { get; set; }
        public int ngaysl_year { get; set; }
        public Nullable<int> diem_QST { get; set; }
        public Nullable<int> ketqua_QST { get; set; }
        public string manhom_tbh { get; set; }
    
        public virtual BVTL_KHACH_HANG BVTL_KHACH_HANG { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
