//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_API
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BVTL_API()
        {
            this.BVTL_MASTER_TABLE = new HashSet<BVTL_MASTER_TABLE>();
        }
    
        public int Api_Id { get; set; }
        public string Api_Code { get; set; }
        public string NameSyncdata { get; set; }
        public string HrefApi { get; set; }
        public string TypeApi { get; set; }
        public string TokenApi { get; set; }
        public string TableNameSaveData { get; set; }
        public bool IsActive { get; set; }
        public string ReportId { get; set; }
        public Nullable<int> TimeReCall { get; set; }
        public string maduan { get; set; }
        public Nullable<System.DateTime> Start_Time_Sync { get; set; }
        public Nullable<System.DateTime> End_Time_Sync { get; set; }
        public string Message { get; set; }
        public string RawOrLabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BVTL_MASTER_TABLE> BVTL_MASTER_TABLE { get; set; }
    }
}
