//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BVTL_QT_NGUOI_DUNG_NHOM_TBH
    {
        public int Id { get; set; }
        public int NguoiDungId { get; set; }
        public string NhomTBHMa { get; set; }
        public bool IsActive { get; set; }
    }
}
