//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_SANG_LOC_HIV
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public Nullable<System.DateTime> ngayhoi { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string hiv { get; set; }
        public string hiv_text { get; set; }
        public string dt_hiv { get; set; }
        public string dt_hiv_text { get; set; }
        public string kqxn { get; set; }
        public string kqxn_text { get; set; }
        public Nullable<int> sng_lc_hiv_complete { get; set; }
        public string city_code { get; set; }
    }
}
