//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_SINH_HOAT_NHOM
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> ngay_shn { get; set; }
        public string chude { get; set; }
        public string phatvatpham { get; set; }
        public string bcs { get; set; }
        public string gel { get; set; }
        public Nullable<int> sinh_hot_nhm_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public string city_code_map { get; set; }
        public string tg { get; set; }
    }
}
