//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_THEO_DAU
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> time_theodau { get; set; }
        public string kq_theodau { get; set; }
        public string lydo_matdau { get; set; }
        public string matdau_khac { get; set; }
        public Nullable<int> theo_du_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    }
}
