//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_DANH_GIA_TAC_DONG
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public Nullable<System.DateTime> date_vi { get; set; }
        public string s2_vi { get; set; }
        public Nullable<int> phng_vn_nh_gi_tc_ng_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public string city_code_map { get; set; }
    }
}
