//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_HANH_VI_NGUY_CO
    {
        public int Id { get; set; }
        public string record_id { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public Nullable<System.DateTime> thoi_gian_bat_dau { get; set; }
        public Nullable<System.DateTime> thoi_gian_ket_thuc { get; set; }
        public string city_code { get; set; }
        public string f1_q_a3 { get; set; }
        public string f1_q_a3_1 { get; set; }
        public string f1_q_a4 { get; set; }
        public string f1_q_a5 { get; set; }
        public string f1_q_a5___1 { get; set; }
        public string f1_q_a5___2 { get; set; }
        public string f1_q_a5___3 { get; set; }
        public string f1_q_a6 { get; set; }
        public string f1_q_a6_1 { get; set; }
        public string f1_q_b1 { get; set; }
        public string f1_q_b1_1 { get; set; }
        public string f1_q_b2 { get; set; }
        public string f1_q_b2_1 { get; set; }
        public string f1_q_b3 { get; set; }
        public string f1_q_b3_1 { get; set; }
        public string f1_q_b4 { get; set; }
        public string f1_q_b4_1 { get; set; }
        public string f1_q_b5 { get; set; }
        public string f1_q_b5_1 { get; set; }
        public string f1_q_b6 { get; set; }
        public string f1_q_b7 { get; set; }
        public string f1_q_b8 { get; set; }
        public string f1_q_b8_1 { get; set; }
        public string f1_q_b9 { get; set; }
        public string f1_q_b10 { get; set; }
        public string f1_q_b11 { get; set; }
        public string f1_q_b12 { get; set; }
        public string f1_q_b13 { get; set; }
        public string f1_q_b14 { get; set; }
        public string f1_q_b14_1 { get; set; }
        public string f1_q_b15 { get; set; }
        public string f1_q_b16 { get; set; }
        public string f1_q_b17 { get; set; }
        public string assist_mota { get; set; }
        public string thuocla { get; set; }
        public string thucuong { get; set; }
        public string cansa { get; set; }
        public string cocain { get; set; }
        public string chatkichthich { get; set; }
        public string khixong { get; set; }
        public string thuocanthan { get; set; }
        public string chatgayaogiac { get; set; }
        public string thuocphien { get; set; }
        public string chatkhac { get; set; }
        public string cacchatkhac { get; set; }
        public string thuocla1 { get; set; }
        public string thucuong1 { get; set; }
        public string cansa1 { get; set; }
        public string coca1 { get; set; }
        public string chatkichthich1 { get; set; }
        public string khixong1 { get; set; }
        public string thuocanthan1 { get; set; }
        public string chatgayaogiac1 { get; set; }
        public string chatthuocphien1 { get; set; }
        public string chatkhac1 { get; set; }
        public string thuocla2 { get; set; }
        public string thucuong2 { get; set; }
        public string cansa2 { get; set; }
        public string coca2 { get; set; }
        public string chatkichthich2 { get; set; }
        public string khixong2 { get; set; }
        public string thuocanthan2 { get; set; }
        public string chatgayaogiac2 { get; set; }
        public string chatthuocphien2 { get; set; }
        public string chatkhac2 { get; set; }
        public string thuocla3 { get; set; }
        public string thucuong3 { get; set; }
        public string cansa3 { get; set; }
        public string coca3 { get; set; }
        public string chatkichthich3 { get; set; }
        public string khixong3 { get; set; }
        public string thuocanthan3 { get; set; }
        public string chatgayaogiac3 { get; set; }
        public string chatthuocphien3 { get; set; }
        public string chatkhac3 { get; set; }
        public string thucuong4 { get; set; }
        public string cansa4 { get; set; }
        public string coca4 { get; set; }
        public string chatkichthich4 { get; set; }
        public string khixong4 { get; set; }
        public string thuocanthan4 { get; set; }
        public string chatgayaogiac4 { get; set; }
        public string chatthuocphien4 { get; set; }
        public string chatkhac4 { get; set; }
        public string thuocla5 { get; set; }
        public string thucuong5 { get; set; }
        public string cansa5 { get; set; }
        public string coca5 { get; set; }
        public string chatkichthich5 { get; set; }
        public string khixong5 { get; set; }
        public string thuocanthan5 { get; set; }
        public string chatgayaogiac5 { get; set; }
        public string chatthuocphien5 { get; set; }
        public string chatkhac5 { get; set; }
        public string thuocla6 { get; set; }
        public string thucuong6 { get; set; }
        public string cansa6 { get; set; }
        public string coca6 { get; set; }
        public string chatkichthich6 { get; set; }
        public string khixong6 { get; set; }
        public string thuocanthan6 { get; set; }
        public string chatgayaogiac6 { get; set; }
        public string chatthuocphien6 { get; set; }
        public string chatkhac6 { get; set; }
        public string cau_8 { get; set; }
        public string diemthuocla { get; set; }
        public string diemthucuong { get; set; }
        public string diemcansa { get; set; }
        public string diemcoca { get; set; }
        public string diemchatkichthich { get; set; }
        public string diemkhixong { get; set; }
        public string diemchatanthan { get; set; }
        public string diemchatgayaogiac { get; set; }
        public string diemchatthuocphien { get; set; }
        public string diemchatkhac { get; set; }
        public string c_1a { get; set; }
        public string c_1b { get; set; }
        public string c_1c { get; set; }
        public string c_1d { get; set; }
        public string c_2 { get; set; }
        public string c_3 { get; set; }
        public string c_4a { get; set; }
        public string c_4b { get; set; }
        public string c_4c { get; set; }
        public string tongdiem { get; set; }
        public string duongtinh { get; set; }
        public string amtinh { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
        public string c7 { get; set; }
        public string c8 { get; set; }
        public string c9 { get; set; }
        public string c10 { get; set; }
        public string diem { get; set; }
        public Nullable<int> thng_tin_c_bn_v_hnh_vi_nguy_c_assist_qst_ace_complete { get; set; }
        public Nullable<System.DateTime> ngayhoi { get; set; }
    }
}
