//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_CHUYEN_GUI
    {
        public int Id { get; set; }
        public string record_id { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public string chuyengui___1 { get; set; }
        public string chuyengui___2 { get; set; }
        public string chuyengui___3 { get; set; }
        public string chuyengui___4 { get; set; }
        public string chuyengui___5 { get; set; }
        public string chuyengui___6 { get; set; }
        public string p_1 { get; set; }
        public Nullable<System.DateTime> f2_q_1_1 { get; set; }
        public string f2_q_1_2 { get; set; }
        public string f2_q_1_3 { get; set; }
        public string f2_q_1_3_1 { get; set; }
        public string f2_q_1_4 { get; set; }
        public string f2_q_1_5 { get; set; }
        public string f2_q_1_5_1 { get; set; }
        public string f2_q_1_6 { get; set; }
        public string f2_q_1_8 { get; set; }
        public Nullable<System.DateTime> f2_q_1_8_1 { get; set; }
        public string p_2 { get; set; }
        public Nullable<System.DateTime> f2_q_2_1 { get; set; }
        public string f2_q_2_2 { get; set; }
        public string f2_q_2_3 { get; set; }
        public string f2_q_2_4 { get; set; }
        public string f2_q_2_5 { get; set; }
        public Nullable<System.DateTime> f2_q_2_6 { get; set; }
        public string p_3 { get; set; }
        public string f2_q_3_1 { get; set; }
        public string f2_q_3_1_1 { get; set; }
        public string f2_q_3_1_1_1 { get; set; }
        public string f2_q_3_1_2 { get; set; }
        public string f2_q_3_1_1_2 { get; set; }
        public string f2_q_3_1_3 { get; set; }
        public string f2_q_3_1_3_1 { get; set; }
        public string f2_q_3_2 { get; set; }
        public string f2_q_3_3 { get; set; }
        public string p_4 { get; set; }
        public string loaihinh4 { get; set; }
        public string loaihinh4___1 { get; set; }
        public string loaihinh4___2 { get; set; }
        public string loaihinh4___3 { get; set; }
        public string loaihinh4___4 { get; set; }
        public string f2_q_4_1 { get; set; }
        public string f2_q_4_1_1 { get; set; }
        public string f2_q_4_1_2 { get; set; }
        public string f2_q_4_1_3 { get; set; }
        public string f2_q_4_1_4 { get; set; }
        public string f2_q_4_1_4___1 { get; set; }
        public string f2_q_4_1_4___2 { get; set; }
        public string f2_q_4_1_4___3 { get; set; }
        public string f2_q_4_1_4___4 { get; set; }
        public string f2_q_4_1_4___5 { get; set; }
        public string f2_q_4_1_4___6 { get; set; }
        public string f2_q_4_1_4___7 { get; set; }
        public string f2_q_4_1_4_1 { get; set; }
        public string f2_q_4_1_5 { get; set; }
        public string f2_q_4_1_6 { get; set; }
        public string f2_q_4_1_7 { get; set; }
        public string f2_q_4_2 { get; set; }
        public Nullable<System.DateTime> f2_q_4_2_1 { get; set; }
        public string f2_q_4_2_2 { get; set; }
        public string f2_q_4_2_3 { get; set; }
        public string f2_q_4_2_4 { get; set; }
        public string f2_q_4_2_5 { get; set; }
        public string f2_q_4_2_6 { get; set; }
        public string f2_q_4_3 { get; set; }
        public Nullable<System.DateTime> f2_q_4_3_1 { get; set; }
        public string f2_q_4_3_2 { get; set; }
        public string f2_q_4_3_3 { get; set; }
        public string f2_q_4_3_4 { get; set; }
        public string f2_q_4_4 { get; set; }
        public Nullable<System.DateTime> f2_q_4_4_1 { get; set; }
        public string f2_q_4_4_2 { get; set; }
        public string f2_q_4_4_2_1 { get; set; }
        public string f2_q_4_4_3 { get; set; }
        public string f2_q_4_4_3_1 { get; set; }
        public string f2_q_4_4_4 { get; set; }
        public string p_5 { get; set; }
        public string f2_q_5 { get; set; }
        public Nullable<System.DateTime> f2_q_5_d { get; set; }
        public string f2_q_51 { get; set; }
        public string f2_q_5_1 { get; set; }
        public string f2_q_53 { get; set; }
        public string f2_q_5_2 { get; set; }
        public string p_6 { get; set; }
        public Nullable<System.DateTime> f2_q_6_d { get; set; }
        public string f2_q_6_1 { get; set; }
        public string f2_q_6_2 { get; set; }
        public string f2_q_6_3 { get; set; }
        public string f2_q_6_4 { get; set; }
        public string f2_q_6_5 { get; set; }
        public string f2_q_6_6 { get; set; }
        public string f2_q_6_7 { get; set; }
        public string chuyn_gi_complete { get; set; }
    }
}
