//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_PHIEU_TU_VAN
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public string redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> ngaytuvan { get; set; }
        public string diadiem { get; set; }
        public string tcv { get; set; }
        public string lantuvan { get; set; }
        public string cau1_1___1 { get; set; }
        public string cau1_1___2 { get; set; }
        public string cau1_1___3 { get; set; }
        public string cau1_1___4 { get; set; }
        public string cau1_1___5 { get; set; }
        public string cau1_1___6 { get; set; }
        public string cau1_1___7 { get; set; }
        public string cau1_1k { get; set; }
        public string cau1_2 { get; set; }
        public string cau1_3___8 { get; set; }
        public string cau1_3___9 { get; set; }
        public string cau1_3___10 { get; set; }
        public string cau1_3___11 { get; set; }
        public string cau_1_4_1___1 { get; set; }
        public string cau_1_4_1___2 { get; set; }
        public string cau_1_4_1___3 { get; set; }
        public string cau_1_4_1___4 { get; set; }
        public string cau_1_4_1___5 { get; set; }
        public string cau_1_4_1___6 { get; set; }
        public string cau_1_4_1___7 { get; set; }
        public string cau_1_4_2 { get; set; }
        public string cau_1_4_1_mt { get; set; }
        public string cau_1_5_2 { get; set; }
        public string cau_1_5_3 { get; set; }
        public string cau_1_5_4 { get; set; }
        public string cau_1_5_5 { get; set; }
        public string cau_1_5_6 { get; set; }
        public string cau2___1 { get; set; }
        public string cau2___2 { get; set; }
        public string cau2___3 { get; set; }
        public string cau2___4 { get; set; }
        public string cau2___5 { get; set; }
        public string cau2___6 { get; set; }
        public string cau2___7 { get; set; }
        public string cau2_1k { get; set; }
        public string cau2_2 { get; set; }
        public string cau3___1 { get; set; }
        public string cau3___2 { get; set; }
        public string cau3___3 { get; set; }
        public string cau3___4 { get; set; }
        public string cau3___5 { get; set; }
        public string cau3___6 { get; set; }
        public string cau3___7 { get; set; }
        public string cau3___8 { get; set; }
        public string cau3___10 { get; set; }
        public string cau3___9 { get; set; }
        public string cau3___11 { get; set; }
        public string cau3___12 { get; set; }
        public string cau3_1k { get; set; }
        public string cau3_1k_2 { get; set; }
        public string cau4___1 { get; set; }
        public string cau4___2 { get; set; }
        public string cau4___3 { get; set; }
        public string cau4___4 { get; set; }
        public string cau4___5 { get; set; }
        public string cau4___6 { get; set; }
        public string cau4___7 { get; set; }
        public string cau4___8 { get; set; }
        public string cau4___9 { get; set; }
        public string cau4___10 { get; set; }
        public string cau4___11 { get; set; }
        public string cau4___12 { get; set; }
        public string cau4_1k { get; set; }
        public string cau4_1k_2 { get; set; }
        public string cau_5___1 { get; set; }
        public string cau_5___2 { get; set; }
        public string cau_5___3 { get; set; }
        public string cau_5___4 { get; set; }
        public string cau_5___6 { get; set; }
        public string cau_5___5 { get; set; }
        public string sktd_khac { get; set; }
        public string cau6_1___1 { get; set; }
        public string cau6_1___2 { get; set; }
        public string cau6_1___3 { get; set; }
        public string cau6_1___4 { get; set; }
        public string cau6_1___5 { get; set; }
        public string cau6_1___6 { get; set; }
        public string cau6_1k { get; set; }
        public string cau6_1_2 { get; set; }
        public string cau6_2___6 { get; set; }
        public string cau6_2___7 { get; set; }
        public string cau6_2___8 { get; set; }
        public string cau6_2___9 { get; set; }
        public string cau6_2___10 { get; set; }
        public string cau6_2___11 { get; set; }
        public string cau6_2___12 { get; set; }
        public string cau6_2___15 { get; set; }
        public string cau6_2___13 { get; set; }
        public string cau6_2___14 { get; set; }
        public string cau6_2k { get; set; }
        public string cau6_2k_2 { get; set; }
        public string cau6_3_bs___1 { get; set; }
        public string cau6_3_bs___2 { get; set; }
        public string cau6_3_bs___3 { get; set; }
        public string cau6_3_bs___4 { get; set; }
        public string cau6_3_bs___5 { get; set; }
        public string cau6_3_bs___6 { get; set; }
        public string cau6_3_bs_1 { get; set; }
        public string cau6_3_bs_2 { get; set; }
        public string cau6_3 { get; set; }
        public string cau6_3_1 { get; set; }
        public string cau6_3_2 { get; set; }
        public string cau6_4 { get; set; }
        public string cau6_4_1 { get; set; }
        public string cau6_5 { get; set; }
        public string cau6_5_1 { get; set; }
        public string tuvantiep { get; set; }
        public string vande { get; set; }
        public string thoigian { get; set; }
        public string phiu_t_vn_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    }
}
