//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD43_KHACH_HANG_DANH_GIA_HAI_LONG
    {
        public long id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> ngay_3db24b { get; set; }
        public Nullable<int> dichvu { get; set; }
        public string dv_khac { get; set; }
        public Nullable<int> cau1 { get; set; }
        public Nullable<int> cau2_b127b4 { get; set; }
        public Nullable<int> cau3_eaf641 { get; set; }
        public Nullable<int> cau4_60e585 { get; set; }
        public Nullable<int> cau5 { get; set; }
        public string cau6 { get; set; }
        public string kenh___1 { get; set; }
        public string kenh___2 { get; set; }
        public string kenh___3 { get; set; }
        public string kenh___4 { get; set; }
        public string khac_1 { get; set; }
        public string thongtin___1 { get; set; }
        public string thongtin___2 { get; set; }
        public string thongtin___3 { get; set; }
        public string thongtin___4 { get; set; }
        public string thongtin___5 { get; set; }
        public string thongtin___6 { get; set; }
        public string tt_khac { get; set; }
        public string chiase { get; set; }
        public Nullable<int> nh_gi_mc_hi_lng_ca_kh_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    }
}
