//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_PHIEU_XET_NGHIEM_LAI_HIV
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<int> solan { get; set; }
        public Nullable<System.DateTime> ngayxetnghiem { get; set; }
        public Nullable<int> kqxn_lai { get; set; }
        public Nullable<int> phiu_xt_nghim_li_hiv_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string ma_tinh { get; set; }
    }
}
