//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_THONG_TIN_CO_BAN
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> doituong { get; set; }
        public Nullable<int> gioitinh { get; set; }
        public Nullable<int> namsinh { get; set; }
        public Nullable<int> tuoi { get; set; }
        public Nullable<int> thng_tin_c_bn_assist_qst_kin_thc_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> ngaytuvan { get; set; }
        public Nullable<System.DateTime> ngaynhap_tuvan { get; set; }
        public Nullable<System.DateTime> ngay_29b439 { get; set; }
        public Nullable<System.DateTime> ngayxetnghiem { get; set; }
        public Nullable<System.DateTime> ngay_7794e9 { get; set; }
        public Nullable<System.DateTime> ngay_ace { get; set; }
        public Nullable<System.DateTime> ngayhoi { get; set; }
        public Nullable<int> sng_lc_nc_tiu_complete { get; set; }
        public Nullable<int> phiu_t_vn_complete { get; set; }
        public Nullable<int> chuyn_gi_dch_v_complete { get; set; }
        public Nullable<int> phiu_xt_nghim_li_hiv_complete { get; set; }
        public Nullable<int> theo_du_kh_complete { get; set; }
        public Nullable<int> bng_hi_ace_complete { get; set; }
        public string ma_tinh { get; set; }
        public Nullable<System.DateTime> ngayhoi_fdf6e6 { get; set; }
        public Nullable<System.DateTime> ngay_xn { get; set; }
        public Nullable<System.DateTime> ngaykham { get; set; }
    }
}
