//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_CHUYEN_GUI
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<int> loaihinh { get; set; }
        public Nullable<System.DateTime> ngay_xn { get; set; }
        public string diachi_xn { get; set; }
        public Nullable<int> kq_xn { get; set; }
        public Nullable<int> dieutri { get; set; }
        public string diachi_cg { get; set; }
        public Nullable<System.DateTime> ngay_bddt { get; set; }
        public Nullable<int> taiuong_bd { get; set; }
        public Nullable<int> taiuong_bd_2 { get; set; }
        public Nullable<int> dt_arv { get; set; }
        public Nullable<System.DateTime> thoidiem { get; set; }
        public string lydo { get; set; }
        public Nullable<System.DateTime> ngaykham { get; set; }
        public string diachikham { get; set; }
        public Nullable<int> lankham { get; set; }
        public Nullable<int> chandoan { get; set; }
        public string khac { get; set; }
        public Nullable<int> kedon { get; set; }
        public Nullable<int> dungthuoc { get; set; }
        public Nullable<int> taikham { get; set; }
        public Nullable<System.DateTime> ngay_taikham { get; set; }
        public Nullable<System.DateTime> ngaykxn { get; set; }
        public string diachi_kxn { get; set; }
        public Nullable<int> lan_xnk { get; set; }
        public Nullable<int> chandoan1 { get; set; }
        public string khac_sti { get; set; }
        public Nullable<int> dieutri_sti { get; set; }
        public Nullable<System.DateTime> ngay_29b439 { get; set; }
        public Nullable<int> mua_bhyt { get; set; }
        public Nullable<int> dt_prep { get; set; }
        public string cs_prep { get; set; }
        public Nullable<int> dt_pep { get; set; }
        public string cs_pep { get; set; }
        public Nullable<int> dt_vgc { get; set; }
        public string cs_vgc { get; set; }
        public Nullable<int> dt_lao { get; set; }
        public string cs_lao { get; set; }
        public Nullable<int> dt_met { get; set; }
        public string cs_met { get; set; }
        public Nullable<int> chuyn_gi_dch_v_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
