//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_THEO_DAU
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> ngay_7794e9 { get; set; }
        public Nullable<int> hinhthuc { get; set; }
        public string hinhthuc_khac { get; set; }
        public Nullable<int> kq { get; set; }
        public string khac_a7b30e { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> theo_du_kh_complete { get; set; }
        public string ma_tinh { get; set; }
    }
}
