//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_BANG_HOI_ACE
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> ngay_ace { get; set; }
        public Nullable<int> c1 { get; set; }
        public Nullable<int> c2 { get; set; }
        public Nullable<int> c3 { get; set; }
        public Nullable<int> c4 { get; set; }
        public Nullable<int> c5 { get; set; }
        public Nullable<int> c6 { get; set; }
        public Nullable<int> c7 { get; set; }
        public Nullable<int> c8 { get; set; }
        public Nullable<int> c9 { get; set; }
        public Nullable<int> c10 { get; set; }
        public Nullable<int> diem { get; set; }
        public Nullable<int> bng_hi_ace_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
