//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_SANG_LOC_HIV
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<int> arv { get; set; }
        public string cs_dieutri { get; set; }
        public Nullable<int> hiv { get; set; }
        public Nullable<System.DateTime> ngayhoi_fdf6e6 { get; set; }
        public Nullable<int> kqxn { get; set; }
        public Nullable<int> lydo { get; set; }
        public Nullable<int> sng_lc_hiv_complete { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    }
}
