//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_THONG_TIN_CO_BAN
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string redcap_repeat_instrument { get; set; }
        public Nullable<int> redcap_repeat_instance { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> doituong { get; set; }
        public Nullable<int> gioitinh { get; set; }
        public Nullable<int> namsinh { get; set; }
        public Nullable<int> tuoi { get; set; }
        public Nullable<int> thng_tin_c_bn_assist_qst_kin_thc_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
    }
}
