//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_THONG_TIN_TRUYEN_THONG
    {
        public int id { get; set; }
        public string makh { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<int> ngayth_date { get; set; }
        public Nullable<int> ngayth_month { get; set; }
        public Nullable<int> ngayth_year { get; set; }
        public string diadiem { get; set; }
        public string noidung { get; set; }
        public Nullable<int> sokh { get; set; }
        public Nullable<int> bcs { get; set; }
        public Nullable<int> gel { get; set; }
        public string ghichu { get; set; }
        public string ch_07_thng_tin_truyn_thng_complete { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public Nullable<int> tailieu { get; set; }
        public int record_id { get; set; }
        public string dichvu { get; set; }
        public string ma_tinh { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_DU_AN BVTL_DU_AN { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
