//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH07_KHACH_HANG_PHIEU_TU_VAN
    {
        public int id { get; set; }
        public string record_id { get; set; }
        public string maduan { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> ngaynhap_tuvan { get; set; }
        public Nullable<System.DateTime> ngaytuvan { get; set; }
        public string diadiem { get; set; }
        public string tcv { get; set; }
        public Nullable<int> lantuvan { get; set; }
        public Nullable<int> cau1_1___1 { get; set; }
        public Nullable<int> cau1_1___2 { get; set; }
        public Nullable<int> cau1_1___3 { get; set; }
        public Nullable<int> cau1_1___4 { get; set; }
        public Nullable<int> cau1_1___5 { get; set; }
        public Nullable<int> cau1_1___6 { get; set; }
        public Nullable<int> cau1_1___7 { get; set; }
        public string cau1_1k { get; set; }
        public string cau1_2 { get; set; }
        public Nullable<int> cau1_3___8 { get; set; }
        public Nullable<int> cau1_3___9 { get; set; }
        public Nullable<int> cau1_3___10 { get; set; }
        public Nullable<int> cau1_3___11 { get; set; }
        public Nullable<int> cau_1_4___1 { get; set; }
        public Nullable<int> cau_1_4___2 { get; set; }
        public Nullable<int> cau_1_4___3 { get; set; }
        public Nullable<int> cau_1_4___4 { get; set; }
        public Nullable<int> cau_1_4___5 { get; set; }
        public Nullable<int> cau_1_4___6 { get; set; }
        public Nullable<int> cau_1_4___7 { get; set; }
        public string cau_1_4_2 { get; set; }
        public string cau_1_4_1_mt { get; set; }
        public string cau_1_5 { get; set; }
        public string cau_1_5_2 { get; set; }
        public string cau_1_5_3 { get; set; }
        public string cau_1_5_4 { get; set; }
        public string cau_1_5_5 { get; set; }
        public string cau_1_5_6 { get; set; }
        public Nullable<int> cau2_852460___1 { get; set; }
        public Nullable<int> cau2_852460___2 { get; set; }
        public Nullable<int> cau2_852460___3 { get; set; }
        public Nullable<int> cau2_852460___4 { get; set; }
        public Nullable<int> cau2_852460___5 { get; set; }
        public Nullable<int> cau2_852460___6 { get; set; }
        public string cau2_1k { get; set; }
        public string cau2_2 { get; set; }
        public Nullable<int> cau3_6aaf33 { get; set; }
        public Nullable<int> cau3_6aaf33___1 { get; set; }
        public Nullable<int> cau3_6aaf33___2 { get; set; }
        public Nullable<int> cau3_6aaf33___3 { get; set; }
        public Nullable<int> cau3_6aaf33___4 { get; set; }
        public Nullable<int> cau3_6aaf33___5 { get; set; }
        public Nullable<int> cau3_6aaf33___6 { get; set; }
        public Nullable<int> cau3_6aaf33___7 { get; set; }
        public Nullable<int> cau3_6aaf33___8 { get; set; }
        public Nullable<int> cau3_6aaf33___9 { get; set; }
        public Nullable<int> cau3_6aaf33___10 { get; set; }
        public Nullable<int> cau3_6aaf33___11 { get; set; }
        public Nullable<int> cau3_6aaf33___12 { get; set; }
        public string cau3_1k { get; set; }
        public string cau3_1k_2 { get; set; }
        public Nullable<int> cau_4 { get; set; }
        public Nullable<int> cau_4___1 { get; set; }
        public Nullable<int> cau_4___2 { get; set; }
        public Nullable<int> cau_4___3 { get; set; }
        public Nullable<int> cau_4___4 { get; set; }
        public Nullable<int> cau_4___5 { get; set; }
        public Nullable<int> cau_4___6 { get; set; }
        public Nullable<int> cau_4___7 { get; set; }
        public Nullable<int> cau_4___8 { get; set; }
        public Nullable<int> cau_4___9 { get; set; }
        public Nullable<int> cau_4___10 { get; set; }
        public Nullable<int> cau_4___11 { get; set; }
        public Nullable<int> cau_4___12 { get; set; }
        public string cau4_1k { get; set; }
        public string cau4_1k_2 { get; set; }
        public Nullable<int> cau_5 { get; set; }
        public Nullable<int> cau_5___1 { get; set; }
        public Nullable<int> cau_5___2 { get; set; }
        public Nullable<int> cau_5___3 { get; set; }
        public Nullable<int> cau_5___4 { get; set; }
        public Nullable<int> cau_5___5 { get; set; }
        public Nullable<int> cau_5___6 { get; set; }
        public string cau_5_1 { get; set; }
        public string cau_5_2 { get; set; }
        public Nullable<int> cau_6_1 { get; set; }
        public Nullable<int> cau_6_1___1 { get; set; }
        public Nullable<int> cau_6_1___2 { get; set; }
        public Nullable<int> cau_6_1___3 { get; set; }
        public Nullable<int> cau_6_1___4 { get; set; }
        public Nullable<int> cau_6_1___5 { get; set; }
        public Nullable<int> cau_6_1___6 { get; set; }
        public string cau6_1k { get; set; }
        public string cau6_1_2 { get; set; }
        public Nullable<int> cau_6_2 { get; set; }
        public Nullable<int> cau_6_2___1 { get; set; }
        public Nullable<int> cau_6_2___2 { get; set; }
        public Nullable<int> cau_6_2___3 { get; set; }
        public Nullable<int> cau_6_2___4 { get; set; }
        public Nullable<int> cau_6_2___5 { get; set; }
        public Nullable<int> cau_6_2___6 { get; set; }
        public Nullable<int> cau_6_2___7 { get; set; }
        public Nullable<int> cau_6_2___8 { get; set; }
        public Nullable<int> cau_6_2___9 { get; set; }
        public Nullable<int> cau_6_2___10 { get; set; }
        public string cau_6_2_1 { get; set; }
        public string cau_6_2_2 { get; set; }
        public Nullable<int> cau_6_3 { get; set; }
        public Nullable<int> cau_6_3___1 { get; set; }
        public Nullable<int> cau_6_3___2 { get; set; }
        public Nullable<int> cau_6_3___3 { get; set; }
        public Nullable<int> cau_6_3___4 { get; set; }
        public Nullable<int> cau_6_3___5 { get; set; }
        public Nullable<int> cau_6_3___6 { get; set; }
        public string cau_6_3_1 { get; set; }
        public string cau_6_3_2 { get; set; }
        public Nullable<int> cau_6_4 { get; set; }
        public string cau_6_4_1 { get; set; }
        public Nullable<int> cau_6_5 { get; set; }
        public Nullable<int> cau_6_5_1 { get; set; }
        public Nullable<int> cau_6_6 { get; set; }
        public Nullable<int> cau_6_6_1 { get; set; }
        public Nullable<int> tongket { get; set; }
        public Nullable<int> tuvantiep { get; set; }
        public string vande { get; set; }
        public string thoigian { get; set; }
        public Nullable<int> phiu_t_vn_complete { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string ma_tinh { get; set; }
    }
}
