//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuatNhap
    {
        public int Id { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public string MaSanPham { get; set; }
        public string MaPhieu { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> LoaiPhieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    }
}
