//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIEU_DUAN
    {
        public int ID_CHITIEU { get; set; }
        public string STT { get; set; }
        public string MOTA { get; set; }
        public int CHITIEU { get; set; }
        public string DONVI { get; set; }
        public string MADUAN { get; set; }
    }
}
