//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryService
    {
        public int Id { get; set; }
        public string CodeTCV { get; set; }
        public string Customer_Code { get; set; }
        public int DayDelivery { get; set; }
        public int MonthDelivery { get; set; }
        public int YearDelivery { get; set; }
        public string Note { get; set; }
        public int CityId { get; set; }
        public int TestGroupId { get; set; }
        public string PREP { get; set; }
        public string PEP { get; set; }
        public string STIs { get; set; }
        public string VGC { get; set; }
        public string Methadone { get; set; }
        public string Other { get; set; }
    }
}
