//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTVTest
    {
        public int Id { get; set; }
        public string CodeTCV { get; set; }
        public string Customer_Code { get; set; }
        public string ResultTest { get; set; }
        public int DayTest { get; set; }
        public int MonthTest { get; set; }
        public int YearTest { get; set; }
        public string Note { get; set; }
        public int CityId { get; set; }
        public int TestGroupId { get; set; }
        public string UnderTreatmentHIV { get; set; }
        public int UserId { get; set; }
    }
}
