//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageAction
    {
        public int ID { get; set; }
        public int PAGE_ID { get; set; }
        public string CONTROL_NAME { get; set; }
        public string CONTROL_DESC { get; set; }
    }
}
