//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageMenu
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_ACTIVE { get; set; }
        public int ORDER_BY { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string HREF_URL { get; set; }
        public Nullable<int> PARENT_PAGE_ID { get; set; }
        public bool IS_SYSTEM_ROLE { get; set; }
    }
}
