//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuatNhap()
        {
            this.ChiTietPhieuXuatNhap = new HashSet<ChiTietPhieuXuatNhap>();
        }
    
        public int Id { get; set; }
        public string MaPhieu { get; set; }
        public int LoaiPhieu { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuatNhap> ChiTietPhieuXuatNhap { get; set; }
    }
}
