//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideReductionItem
    {
        public int Id { get; set; }
        public string CodeTCV { get; set; }
        public string Customer_Code { get; set; }
        public int DayProvide { get; set; }
        public int MonthProvide { get; set; }
        public int YearProvide { get; set; }
        public string Note { get; set; }
        public int CityId { get; set; }
        public int TestGroupId { get; set; }
        public Nullable<int> NumberDocuments { get; set; }
        public Nullable<int> NumberCondom { get; set; }
        public Nullable<int> NumberCBT { get; set; }
    }
}
