//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialSupport
    {
        public int Id { get; set; }
        public string CodeTCV { get; set; }
        public string Customer_Code { get; set; }
        public int DaySupport { get; set; }
        public int MonthSupport { get; set; }
        public int YearSupport { get; set; }
        public string Note { get; set; }
        public int CityId { get; set; }
        public int TestGroupId { get; set; }
        public string BuyBHYT { get; set; }
        public string RegistrationPersonalDocuments { get; set; }
        public string Loans { get; set; }
        public string Juridical { get; set; }
        public string ApprenticeshipIntroduction { get; set; }
        public string JobIntroduction { get; set; }
    }
}
