//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysParameter
    {
        public int ID { get; set; }
        public string ParamCode { get; set; }
        public string ParamValue { get; set; }
        public string Desctiption { get; set; }
        public bool IsActive { get; set; }
        public string ParamValueType { get; set; }
    }
}
