//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIIV_DANH_GIA_HAI_LONG
    {
        public int record_id { get; set; }
        public string makh { get; set; }
        public System.DateTime ngay { get; set; }
        public int ngayth_date { get; set; }
        public int ngayth_month { get; set; }
        public int ngayth_year { get; set; }
        public Nullable<int> lantuvan { get; set; }
        public Nullable<int> cau1 { get; set; }
        public Nullable<int> cau2 { get; set; }
        public Nullable<int> cau3 { get; set; }
        public Nullable<int> cau4 { get; set; }
        public Nullable<int> cau5 { get; set; }
        public string cau6 { get; set; }
        public string nh_gi_mc_hi_lng_complete { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_DU_AN BVTL_DU_AN { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
