//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIIV_TRAINING_DATA_COLLECTION
    {
        public int record_id { get; set; }
        public string makh { get; set; }
        public System.DateTime thoigian { get; set; }
        public int ngayth_date { get; set; }
        public int ngayth_month { get; set; }
        public int ngayth_year { get; set; }
        public string doituong { get; set; }
        public string taphuan { get; set; }
        public string khac { get; set; }
        public string noidung { get; set; }
        public Nullable<int> nhataitro { get; set; }
        public Nullable<int> nvngo { get; set; }
        public Nullable<int> nvtccd { get; set; }
        public Nullable<int> cbcqnn { get; set; }
        public Nullable<int> nvtv { get; set; }
        public Nullable<int> cbyt { get; set; }
        public Nullable<int> scdi { get; set; }
        public Nullable<int> khac1 { get; set; }
        public Nullable<int> nhataitro_2 { get; set; }
        public Nullable<int> ngo { get; set; }
        public Nullable<int> tochuc1 { get; set; }
        public Nullable<int> qlnn { get; set; }
        public Nullable<int> ccdv { get; set; }
        public Nullable<int> ttcn { get; set; }
        public Nullable<int> bc { get; set; }
        public Nullable<int> scdi1 { get; set; }
        public Nullable<int> scdi2 { get; set; }
        public string tinh { get; set; }
        public string tinh_2 { get; set; }
        public string training_complete { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
        public Nullable<int> record_id_api { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_DU_AN BVTL_DU_AN { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
