//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIIV_TT_KH_MAT_DAU
    {
        public int record_id { get; set; }
        public string makh { get; set; }
        public System.DateTime ngaynl { get; set; }
        public int ngayth_date { get; set; }
        public int ngayth_month { get; set; }
        public int ngayth_year { get; set; }
        public System.DateTime ngay_md { get; set; }
        public string kh_mt_du_complete { get; set; }
        public string manhom_tbh { get; set; }
        public string city_code { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
        public string maduan { get; set; }
    
        public virtual BVTL_CITES BVTL_CITES { get; set; }
        public virtual BVTL_DU_AN BVTL_DU_AN { get; set; }
        public virtual BVTL_NHOM_TBH BVTL_NHOM_TBH { get; set; }
    }
}
